package model;

public enum ModelState {
	REGISTRATION, LOGIN, REGISTRATIONUPDATE, ERRORCONNECTIONDOWN, 
	EXIT, PROMPTRELOAD, UNABLETOOPENSTREAMS, UNABLETOOPENSOCKET, EVENTS, EVENTSUPDATE,
	PROFILE, EDIT, PASSWORD, LOGINUNSUCCESSFULWRONGUSERNAME, LOGINUNSUCCESSFULWRONGPASSWORD
}
