package model;

public enum ModelState {
	REGISTRATION, LOGIN, REGISTRATIONUPDATE, ERRORCONNECTIONDOWN, ERRORCONNECTIONDOWNSTILL, PROMPTRELOAD,
	EXIT, UNABLETOOPENSTREAMS, UNABLETOOPENSOCKET, EVENTS, EVENTSUPDATE,
	PROFILE, EDIT, PASSWORD, LOGINUNSUCCESSFULWRONGUSERNAME, LOGINUNSUCCESSFULWRONGPASSWORD, LOGOUT
}
