package model;

public enum ModelState {
	REGISTRATION, LOGIN, REGISTRATIONUPDATE, ERRORCONNECTIONDOWN, 
	EXIT, PROMPTRELOAD, UNABLETOOPENSTREAMS, UNABLETOOPENSOCKET, LIST, LISTUPDATE,
	PROFILE, EDIT, PASSWORD
}
