package model;

public enum State {
	REGISTRATION, LOGIN,REGISTRATIONUSEREXISTS, REGISTRATIONUSEROK, 
	REGISTRATIONEMAILEXISTS, REGISTRATIONEMAILOK, ERRORCONNECTIONDOWN, 
	ERRORSERVERCOMMUNICATION, EXIT
}
