package model;

public enum ModelState {
	REGISTRATION, LOGIN, REGISTRATIONUPDATE, ERRORCONNECTIONDOWN, ERRORCONNECTIONDOWNSTILL,
	EXIT, UNABLETOOPENSTREAMS, UNABLETOOPENSOCKET, EVENTS, EVENTSUPDATE,
	PROFILE, EDIT, PASSWORD, LOGINUNSUCCESSFULWRONGUSERNAME, LOGINUNSUCCESSFULWRONGPASSWORD
}
